// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json.Linq;
using SwaggerClient0.Models;

namespace SwaggerClient0.Models
{
    public static partial class SaleCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<Sale> DeserializeJson(JToken inputObject)
        {
            IList<Sale> deserializedObject = new List<Sale>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                Sale sale = new Sale();
                sale.DeserializeJson(iListValue);
                deserializedObject.Add(sale);
            }
            return deserializedObject;
        }
    }
}
