// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Net.Http;
using Microsoft.Rest;
using MvcSwaggerClient;

namespace MvcSwaggerClient
{
    public partial class SimpleWebAPIEFCFJoin : ServiceClient<SimpleWebAPIEFCFJoin>, ISimpleWebAPIEFCFJoin
    {
        private Uri _baseUri;
        
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        public Uri BaseUri
        {
            get { return this._baseUri; }
            set { this._baseUri = value; }
        }
        
        private ServiceClientCredentials _credentials;
        
        /// <summary>
        /// Credentials for authenticating with the service.
        /// </summary>
        public ServiceClientCredentials Credentials
        {
            get { return this._credentials; }
            set { this._credentials = value; }
        }
        
        private ISales _sales;
        
        public virtual ISales Sales
        {
            get { return this._sales; }
        }
        
        private ISmallTitles _smallTitles;
        
        public virtual ISmallTitles SmallTitles
        {
            get { return this._smallTitles; }
        }
        
        private ITitles _titles;
        
        public virtual ITitles Titles
        {
            get { return this._titles; }
        }
        
        /// <summary>
        /// Initializes a new instance of the SimpleWebAPIEFCFJoin class.
        /// </summary>
        public SimpleWebAPIEFCFJoin()
            : base()
        {
            this._sales = new Sales(this);
            this._smallTitles = new SmallTitles(this);
            this._titles = new Titles(this);
            this._baseUri = new Uri("http://localhost:53381");
        }
        
        /// <summary>
        /// Initializes a new instance of the SimpleWebAPIEFCFJoin class.
        /// </summary>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public SimpleWebAPIEFCFJoin(params DelegatingHandler[] handlers)
            : base(handlers)
        {
            this._sales = new Sales(this);
            this._smallTitles = new SmallTitles(this);
            this._titles = new Titles(this);
            this._baseUri = new Uri("http://localhost:53381");
        }
        
        /// <summary>
        /// Initializes a new instance of the SimpleWebAPIEFCFJoin class.
        /// </summary>
        /// <param name='rootHandler'>
        /// Optional. The http client handler used to handle http transport.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public SimpleWebAPIEFCFJoin(HttpClientHandler rootHandler, params DelegatingHandler[] handlers)
            : base(rootHandler, handlers)
        {
            this._sales = new Sales(this);
            this._smallTitles = new SmallTitles(this);
            this._titles = new Titles(this);
            this._baseUri = new Uri("http://localhost:53381");
        }
        
        /// <summary>
        /// Initializes a new instance of the SimpleWebAPIEFCFJoin class.
        /// </summary>
        /// <param name='baseUri'>
        /// Optional. The base URI of the service.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public SimpleWebAPIEFCFJoin(Uri baseUri, params DelegatingHandler[] handlers)
            : this(handlers)
        {
            if (baseUri == null)
            {
                throw new ArgumentNullException("baseUri");
            }
            this._baseUri = baseUri;
        }
        
        /// <summary>
        /// Initializes a new instance of the SimpleWebAPIEFCFJoin class.
        /// </summary>
        /// <param name='credentials'>
        /// Required. Credentials for authenticating with the service.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public SimpleWebAPIEFCFJoin(ServiceClientCredentials credentials, params DelegatingHandler[] handlers)
            : this(handlers)
        {
            if (credentials == null)
            {
                throw new ArgumentNullException("credentials");
            }
            this._credentials = credentials;
            
            if (this.Credentials != null)
            {
                this.Credentials.InitializeServiceClient(this);
            }
        }
        
        /// <summary>
        /// Initializes a new instance of the SimpleWebAPIEFCFJoin class.
        /// </summary>
        /// <param name='baseUri'>
        /// Optional. The base URI of the service.
        /// </param>
        /// <param name='credentials'>
        /// Required. Credentials for authenticating with the service.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public SimpleWebAPIEFCFJoin(Uri baseUri, ServiceClientCredentials credentials, params DelegatingHandler[] handlers)
            : this(handlers)
        {
            if (baseUri == null)
            {
                throw new ArgumentNullException("baseUri");
            }
            if (credentials == null)
            {
                throw new ArgumentNullException("credentials");
            }
            this._baseUri = baseUri;
            this._credentials = credentials;
            
            if (this.Credentials != null)
            {
                this.Credentials.InitializeServiceClient(this);
            }
        }
    }
}
