// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Deleeteme.Models;
using Newtonsoft.Json.Linq;

namespace Deleeteme.Models
{
    public static partial class SmallTitleCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<SmallTitle> DeserializeJson(JToken inputObject)
        {
            IList<SmallTitle> deserializedObject = new List<SmallTitle>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                SmallTitle smallTitle = new SmallTitle();
                smallTitle.DeserializeJson(iListValue);
                deserializedObject.Add(smallTitle);
            }
            return deserializedObject;
        }
    }
}
