// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace MvcSwaggerClient.Models
{
    public partial class SmallTitle
    {
        private string _titleID;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string TitleID
        {
            get { return this._titleID; }
            set { this._titleID = value; }
        }
        
        private string _title1;
        
        /// <summary>
        /// Required.
        /// </summary>
        public string Title1
        {
            get { return this._title1; }
            set { this._title1 = value; }
        }
        
        private int? _ytdSales;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? YtdSales
        {
            get { return this._ytdSales; }
            set { this._ytdSales = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the SmallTitle class.
        /// </summary>
        public SmallTitle()
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the smallTitle class with required
        /// arguments.
        /// </summary>
        public SmallTitle(string title1)
            : this()
        {
            if (title1 == null)
            {
                throw new ArgumentNullException("title1");
            }
            this.Title1 = title1;
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken titleIDValue = inputObject["title_id"];
                if (titleIDValue != null && titleIDValue.Type != JTokenType.Null)
                {
                    this.TitleID = ((string)titleIDValue);
                }
                JToken title1Value = inputObject["title1"];
                if (title1Value != null && title1Value.Type != JTokenType.Null)
                {
                    this.Title1 = ((string)title1Value);
                }
                JToken ytdSalesValue = inputObject["ytd_sales"];
                if (ytdSalesValue != null && ytdSalesValue.Type != JTokenType.Null)
                {
                    this.YtdSales = ((int)ytdSalesValue);
                }
            }
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type smallTitle
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.Title1 == null)
            {
                throw new ArgumentNullException("Title1");
            }
            if (this.TitleID != null)
            {
                outputObject["title_id"] = this.TitleID;
            }
            if (this.Title1 != null)
            {
                outputObject["title1"] = this.Title1;
            }
            if (this.YtdSales != null)
            {
                outputObject["ytd_sales"] = this.YtdSales.Value;
            }
            return outputObject;
        }
    }
}
